<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Web_Windows_Chrome_1.2_2"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="486.007">
  <properties />
            <testcase name="testt" time="486.007" classname="AutomationSuites.webApp.P1_TestCases">
                <failure type="java.lang.AssertionError"
                  message="expected [ADD INPUTS] but found [REVIEW]"
              >
<![CDATA[java.lang.AssertionError: expected [ADD INPUTS] but found [REVIEW]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertEqualsImpl(Assert.java:137)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:453)
  org.testng.Assert.assertEquals(Assert.java:463)
  frameworkLibrary.webDriverConfig.assertEquals_Text(webDriverConfig.java:223)
  webApp.MarketingCalenderPage.verifyToolTipData_MarketingCalendarPage(MarketingCalenderPage.java:82)
  webApp.MarketingCalenderPage.verifyData_MarketingCalendarPage(MarketingCalenderPage.java:161)
  AutomationSuites.webApp.P1_TestCases.testt(P1_TestCases.java:43)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
  org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
