<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MD-LAP-017" name="AutomationSuites.webApp.P1_TestCases" tests="1" failures="1" timestamp="28 Feb 2018 10:08:43 GMT" time="486.355" errors="0">
  <testcase name="testt" time="486.355" classname="AutomationSuites.webApp.P1_TestCases">
    <failure type="java.lang.AssertionError" message="expected [ADD INPUTS] but found [REVIEW]">
      <![CDATA[java.lang.AssertionError: expected [ADD INPUTS] but found [REVIEW]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at frameworkLibrary.webDriverConfig.assertEquals_Text(webDriverConfig.java:223)at webApp.MarketingCalenderPage.verifyToolTipData_MarketingCalendarPage(MarketingCalenderPage.java:82)at webApp.MarketingCalenderPage.verifyData_MarketingCalendarPage(MarketingCalenderPage.java:161)at AutomationSuites.webApp.P1_TestCases.testt(P1_TestCases.java:43)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </failure>
  </testcase> <!-- testt -->
</testsuite> <!-- AutomationSuites.webApp.P1_TestCases -->
